
a1 = "CQACAgQAAxkBAAIBmWJxG6GwjjkLW1JojUIIpC35r6c4AAIyAwACCaFEU04ySVHQ3OZYJAQ"  # дешёвые драмы.
a2 = "CQACAgIAAxkBAAIBl2JxG3NSxBpXdy2X5ReQri-NxDNOAAJuGAACg7KISx0Ff3kOP2xdJAQ"  # бесполезно.
a3 = 'CQACAgIAAxkBAAIBkGJxGT1NiqbeFfLUtvfZWH1M_caJAAJoGAACg7KISzisojUXGpW1JAQ'  # рустем.
a4 = "CQACAgQAAxkBAAIBm2JxG9BH7s9doSl4wb70N_UwMR6AAALsAgAC4eFEU2qV22lfVf-VJAQ"  # кладбище самолётов.
a5 = "CQACAgQAAxkBAAIBnWJxG_BFQbLm6IZ3iRKew2JAhleOAAK9AgACXxNEU3_N8hancOXFJAQ"  # космос нас ждёт.
a6 = "CQACAgQAAxkBAAIBn2JxHLthRiZmVmwFOQ7sh4BKyxJYAAIHAwACuAZFU3WVIMlffb-kJAQ"  # так гріє.
a7 = "CQACAgQAAxkBAAIBoWJxHPS5OeavUCe6CgHf4rQEnSpUAAIHAwAChoNEU781OqD4yqGBJAQ"  # ты не такая.
a8 = "CQACAgQAAxkBAAIBo2JxHUJud8MsUZvetvbq6egFrfGdAALgAgACj6FEUyPVMC2EetftJAQ"  # если будет снег.
b1 = "CQACAgQAAxkBAAIBpWJxHW0n1FbjUXUFn9oHpszbb_VMAALZAgACnFpEUydSppLT-6qkJAQ"  # я бью женщин и детей.
b2 = "CQACAgQAAxkBAAIBqWJxHbgZwdOnOxyZNfKGUn6hcA_fAAL9AgACoclEU_aNw9f29BweJAQ"  # все решено
b3 = "CQACAgQAAxkBAAIBq2JxHefRkl-kj5MG-LhNYfNCYGClAAKiAgAC8UZMUwKYKHE3SRv5JAQ"  # первомай
b4 = "CQACAgQAAxkBAAIBrWJxHhYeJ9jaMDGDAYv2K4NnX-ZCAAIEAwACompEU0FaNYGurS9xJAQ"  # лишь однажды.
b5 = "CQACAgQAAxkBAAIBr2JxHkGUhIDJljtoig3RZFD1W0fhAAL0AgACv_NFU6eOdYL2EUwVJAQ"  # сережа .
b6 = "CQACAgQAAxkBAAIBs2JxHnKab2AOJNU4CYS66pPwQgwfAAJKAwACI79FU74FlW8AAcThcyQE"  # все мои друзья.
